==26043== Memcheck, a memory error detector
==26043== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==26043== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==26043== Command: python readGrid.py
==26043== Parent PID: 19217
==26043== 
==26043== 
==26043== HEAP SUMMARY:
==26043==     in use at exit: 658,759 bytes in 373 blocks
==26043==   total heap usage: 1,894 allocs, 1,521 frees, 6,174,946 bytes allocated
==26043== 
==26043== 1 bytes in 1 blocks are still reachable in loss record 1 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49717A4: PyModule_ExecDef (moduleobject.c:388)
==26043==    by 0x4A50AC2: exec_builtin_or_dynamic (import.c:1998)
==26043==    by 0x4A50AC2: _PyImport_BootstrapImp (import.c:2220)
==26043==    by 0x4A64338: init_importlib (pylifecycle.c:180)
==26043==    by 0x4A64338: pycore_interp_init (pylifecycle.c:837)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 6 bytes in 1 blocks are still reachable in loss record 2 of 94
==26043==    at 0x484582F: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49C4ED8: _Py_EncodeUTF8Ex (unicodeobject.c:5591)
==26043==    by 0x49E393B: encode_wstr_utf8 (unicodeobject.c:16172)
==26043==    by 0x49E393B: init_fs_codec (unicodeobject.c:16258)
==26043==    by 0x49E393B: init_fs_encoding (unicodeobject.c:16314)
==26043==    by 0x49E393B: _PyUnicode_InitEncodings (unicodeobject.c:16324)
==26043==    by 0x4A65B43: init_interp_main (pylifecycle.c:1104)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 6 bytes in 1 blocks are still reachable in loss record 3 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497AE41: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497AE41: _PyMem_RawStrdup (obmalloc.c:658)
==26043==    by 0x4A61BCF: _Py_SetFileSystemEncoding (preconfig.c:49)
==26043==    by 0x49E39DB: init_fs_codec (unicodeobject.c:16290)
==26043==    by 0x49E39DB: init_fs_encoding (unicodeobject.c:16314)
==26043==    by 0x49E39DB: _PyUnicode_InitEncodings (unicodeobject.c:16324)
==26043==    by 0x4A65B43: init_interp_main (pylifecycle.c:1104)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 6 bytes in 6 blocks are still reachable in loss record 4 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49717A4: PyModule_ExecDef (moduleobject.c:388)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C77C1: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C77C1: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C77C1: call_function (ceval.c:5891)
==26043==    by 0x48C77C1: _PyEval_EvalFrameDefault (ceval.c:4181)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043== 
==26043== 8 bytes in 1 blocks are still reachable in loss record 5 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A519C6: _PyWideStringList_Copy (initconfig.c:340)
==26043==    by 0x4A52C92: _PyConfig_Copy (initconfig.c:909)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 16 bytes in 1 blocks are still reachable in loss record 6 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A519C6: _PyWideStringList_Copy (initconfig.c:340)
==26043==    by 0x4A55861: _Py_SetArgcArgv (initconfig.c:568)
==26043==    by 0x4A55861: _PyConfig_Write (initconfig.c:2267)
==26043==    by 0x4A66DF5: pycore_init_runtime (pylifecycle.c:564)
==26043==    by 0x4A66DF5: pyinit_config (pylifecycle.c:854)
==26043==    by 0x4A66DF5: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 16 bytes in 1 blocks are still reachable in loss record 7 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A5296E: PyConfig_SetString (initconfig.c:806)
==26043==    by 0x4A52E7F: _PyConfig_Copy (initconfig.c:921)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 16 bytes in 1 blocks are still reachable in loss record 8 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A519C6: _PyWideStringList_Copy (initconfig.c:340)
==26043==    by 0x4A5300A: _PyConfig_Copy (initconfig.c:951)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 16 bytes in 1 blocks are still reachable in loss record 9 of 94
==26043==    at 0x484582F: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49C4ED8: _Py_EncodeUTF8Ex (unicodeobject.c:5591)
==26043==    by 0x49E396A: encode_wstr_utf8 (unicodeobject.c:16172)
==26043==    by 0x49E396A: init_fs_codec (unicodeobject.c:16264)
==26043==    by 0x49E396A: init_fs_encoding (unicodeobject.c:16314)
==26043==    by 0x49E396A: _PyUnicode_InitEncodings (unicodeobject.c:16324)
==26043==    by 0x4A65B43: init_interp_main (pylifecycle.c:1104)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 16 bytes in 1 blocks are still reachable in loss record 10 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497AE41: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497AE41: _PyMem_RawStrdup (obmalloc.c:658)
==26043==    by 0x4A61BE3: _Py_SetFileSystemEncoding (preconfig.c:54)
==26043==    by 0x49E39DB: init_fs_codec (unicodeobject.c:16290)
==26043==    by 0x49E39DB: init_fs_encoding (unicodeobject.c:16314)
==26043==    by 0x49E39DB: _PyUnicode_InitEncodings (unicodeobject.c:16324)
==26043==    by 0x4A65B43: init_interp_main (pylifecycle.c:1104)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 20 bytes in 1 blocks are still reachable in loss record 11 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A6141D: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A6141D: config_init_pathconfig (pathconfig.c:402)
==26043==    by 0x4A6141D: _PyConfig_InitPathConfig (pathconfig.c:438)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 20 bytes in 1 blocks are still reachable in loss record 12 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A61335: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A61335: config_init_pathconfig (pathconfig.c:403)
==26043==    by 0x4A61335: _PyConfig_InitPathConfig (pathconfig.c:438)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 20 bytes in 1 blocks are still reachable in loss record 13 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A6138C: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A6138C: _PyConfig_InitPathConfig (pathconfig.c:445)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 20 bytes in 1 blocks are still reachable in loss record 14 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A613BF: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A613BF: _PyConfig_InitPathConfig (pathconfig.c:451)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 20 bytes in 1 blocks are still reachable in loss record 15 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A6060A: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A6060A: pathconfig_set_from_config (pathconfig.c:168)
==26043==    by 0x4A60C52: _PyConfig_WritePathConfig (pathconfig.c:267)
==26043==    by 0x4A659F0: interpreter_update_config (pylifecycle.c:457)
==26043==    by 0x4A659F0: init_interp_main (pylifecycle.c:1087)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 20 bytes in 1 blocks are still reachable in loss record 16 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A60643: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A60643: pathconfig_set_from_config (pathconfig.c:169)
==26043==    by 0x4A60C52: _PyConfig_WritePathConfig (pathconfig.c:267)
==26043==    by 0x4A659F0: interpreter_update_config (pylifecycle.c:457)
==26043==    by 0x4A659F0: init_interp_main (pylifecycle.c:1087)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 24 bytes in 1 blocks are still reachable in loss record 17 of 94
==26043==    at 0x484582F: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A52026: PyWideStringList_Insert (initconfig.c:383)
==26043==    by 0x4A52026: PyWideStringList_Append (initconfig.c:405)
==26043==    by 0x4A611DF: config_init_module_search_paths (pathconfig.c:294)
==26043==    by 0x4A611DF: config_init_pathconfig (pathconfig.c:377)
==26043==    by 0x4A611DF: _PyConfig_InitPathConfig (pathconfig.c:438)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 24 bytes in 1 blocks are still reachable in loss record 18 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x49C5119: config_get_codec_name (unicodeobject.c:16212)
==26043==    by 0x49E38F6: init_fs_encoding (unicodeobject.c:16308)
==26043==    by 0x49E38F6: _PyUnicode_InitEncodings (unicodeobject.c:16324)
==26043==    by 0x4A65B43: init_interp_main (pylifecycle.c:1104)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 24 bytes in 1 blocks are still reachable in loss record 19 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x49C5119: config_get_codec_name (unicodeobject.c:16212)
==26043==    by 0x49E39F9: init_stdio_encoding (unicodeobject.c:16237)
==26043==    by 0x49E39F9: _PyUnicode_InitEncodings (unicodeobject.c:16329)
==26043==    by 0x4A65B43: init_interp_main (pylifecycle.c:1104)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 28 bytes in 1 blocks are still reachable in loss record 20 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A52C60: PyConfig_SetString (initconfig.c:806)
==26043==    by 0x4A52C60: _PyConfig_Copy (initconfig.c:906)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 28 bytes in 1 blocks are still reachable in loss record 21 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A6067C: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A6067C: pathconfig_set_from_config (pathconfig.c:170)
==26043==    by 0x4A60C52: _PyConfig_WritePathConfig (pathconfig.c:267)
==26043==    by 0x4A659F0: interpreter_update_config (pylifecycle.c:457)
==26043==    by 0x4A659F0: init_interp_main (pylifecycle.c:1087)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 32 bytes in 1 blocks are still reachable in loss record 22 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A7CF64: PyThread_allocate_lock (thread_pthread.h:392)
==26043==    by 0x4A691D2: _PyRuntimeState_Init_impl (pystate.c:78)
==26043==    by 0x4A691D2: _PyRuntimeState_Init (pystate.c:109)
==26043==    by 0x4A665A5: _PyRuntime_Initialize (pylifecycle.c:105)
==26043==    by 0x4A665A5: _PyRuntime_Initialize (pylifecycle.c:92)
==26043==    by 0x4A8E83D: pymain_init (main.c:38)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 32 bytes in 1 blocks are still reachable in loss record 23 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A7CF64: PyThread_allocate_lock (thread_pthread.h:392)
==26043==    by 0x4A691E8: _PyRuntimeState_Init_impl (pystate.c:84)
==26043==    by 0x4A691E8: _PyRuntimeState_Init (pystate.c:109)
==26043==    by 0x4A665A5: _PyRuntime_Initialize (pylifecycle.c:105)
==26043==    by 0x4A665A5: _PyRuntime_Initialize (pylifecycle.c:92)
==26043==    by 0x4A8E83D: pymain_init (main.c:38)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 32 bytes in 1 blocks are still reachable in loss record 24 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A7CF64: PyThread_allocate_lock (thread_pthread.h:392)
==26043==    by 0x4A691FF: _PyRuntimeState_Init_impl (pystate.c:92)
==26043==    by 0x4A691FF: _PyRuntimeState_Init (pystate.c:109)
==26043==    by 0x4A665A5: _PyRuntime_Initialize (pylifecycle.c:105)
==26043==    by 0x4A665A5: _PyRuntime_Initialize (pylifecycle.c:92)
==26043==    by 0x4A8E83D: pymain_init (main.c:38)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 32 bytes in 1 blocks are still reachable in loss record 25 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A7CF64: PyThread_allocate_lock (thread_pthread.h:392)
==26043==    by 0x4A2243E: _PyEval_InitState (ceval.c:818)
==26043==    by 0x4A694DC: PyInterpreterState_New (pystate.c:227)
==26043==    by 0x4A66F84: pycore_create_interpreter (pylifecycle.c:629)
==26043==    by 0x4A66F84: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66F84: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 32 bytes in 1 blocks are still reachable in loss record 26 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A5296E: PyConfig_SetString (initconfig.c:806)
==26043==    by 0x4A52FD8: _PyConfig_Copy (initconfig.c:947)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 32 bytes in 1 blocks are still reachable in loss record 27 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A7CF64: PyThread_allocate_lock (thread_pthread.h:392)
==26043==    by 0x4A4DB84: _PyImport_AcquireLock (import.c:124)
==26043==    by 0x4A4DB84: _imp_acquire_lock_impl (import.c:217)
==26043==    by 0x4A4DB84: _imp_acquire_lock (import.c.h:43)
==26043==    by 0x496FCDD: cfunction_vectorcall_NOARGS (methodobject.c:489)
==26043==    by 0x48C77C1: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C77C1: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C77C1: call_function (ceval.c:5891)
==26043==    by 0x48C77C1: _PyEval_EvalFrameDefault (ceval.c:4181)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x49248AB: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x49248AB: method_vectorcall (classobject.c:61)
==26043==    by 0x48C383D: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C383D: _PyObject_CallNoArg (abstract.h:168)
==26043==    by 0x48C383D: _PyEval_EvalFrameDefault (ceval.c:4081)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x49216AE: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x49216AE: object_vacall (call.c:734)
==26043== 
==26043== 32 bytes in 1 blocks are still reachable in loss record 28 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A7CF64: PyThread_allocate_lock (thread_pthread.h:392)
==26043==    by 0x4AE0AEA: _buffered_init (bufferedio.c:739)
==26043==    by 0x4AE0C7E: _io_BufferedReader___init___impl (bufferedio.c:1447)
==26043==    by 0x4AE0C7E: _io_BufferedReader___init__ (bufferedio.c.h:435)
==26043==    by 0x498B116: type_call (typeobject.c:1135)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:112)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:99)
==26043==    by 0x49219B0: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x49227E3: _PyObject_CallFunction_SizeT (call.c:539)
==26043==    by 0x4ADAC48: _io_open_impl (_iomodule.c:465)
==26043==    by 0x4ADAC48: _io_open (_iomodule.c.h:269)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x492188A: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x492188A: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x4922B98: callmethod (call.c:557)
==26043==    by 0x4922B98: _PyObject_CallMethodId (call.c:627)
==26043== 
==26043== 48 bytes in 1 blocks are still reachable in loss record 29 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A51A05: _PyWideStringList_Copy (initconfig.c:346)
==26043==    by 0x4A52C92: _PyConfig_Copy (initconfig.c:909)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 64 bytes in 1 blocks are still reachable in loss record 30 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A5296E: PyConfig_SetString (initconfig.c:806)
==26043==    by 0x4A52EF4: _PyConfig_Copy (initconfig.c:937)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 64 bytes in 1 blocks are still reachable in loss record 31 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A5296E: PyConfig_SetString (initconfig.c:806)
==26043==    by 0x4A52F3C: _PyConfig_Copy (initconfig.c:939)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 64 bytes in 2 blocks are still reachable in loss record 32 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A7CF64: PyThread_allocate_lock (thread_pthread.h:392)
==26043==    by 0x4AE0AEA: _buffered_init (bufferedio.c:739)
==26043==    by 0x4AE12DE: _io_BufferedWriter___init___impl (bufferedio.c:1801)
==26043==    by 0x4AE12DE: _io_BufferedWriter___init__ (bufferedio.c.h:489)
==26043==    by 0x498B116: type_call (typeobject.c:1135)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:112)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:99)
==26043==    by 0x49219B0: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x49227E3: _PyObject_CallFunction_SizeT (call.c:539)
==26043==    by 0x4ADAC48: _io_open_impl (_iomodule.c:465)
==26043==    by 0x4ADAC48: _io_open (_iomodule.c.h:269)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x492188A: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x492188A: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x4922B98: callmethod (call.c:557)
==26043==    by 0x4922B98: _PyObject_CallMethodId (call.c:627)
==26043== 
==26043== 76 bytes in 2 blocks are still reachable in loss record 33 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A51A05: _PyWideStringList_Copy (initconfig.c:346)
==26043==    by 0x4A55861: _Py_SetArgcArgv (initconfig.c:568)
==26043==    by 0x4A55861: _PyConfig_Write (initconfig.c:2267)
==26043==    by 0x4A66DF5: pycore_init_runtime (pylifecycle.c:564)
==26043==    by 0x4A66DF5: pyinit_config (pylifecycle.c:854)
==26043==    by 0x4A66DF5: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 76 bytes in 2 blocks are still reachable in loss record 34 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A51A05: _PyWideStringList_Copy (initconfig.c:346)
==26043==    by 0x4A5300A: _PyConfig_Copy (initconfig.c:951)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 172 bytes in 1 blocks are still reachable in loss record 35 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A5296E: PyConfig_SetString (initconfig.c:806)
==26043==    by 0x4A52FB4: _PyConfig_Copy (initconfig.c:946)
==26043==    by 0x4A66FA8: pycore_create_interpreter (pylifecycle.c:635)
==26043==    by 0x4A66FA8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FA8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 204 bytes in 1 blocks are still reachable in loss record 36 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A613ED: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A613ED: config_init_pathconfig (pathconfig.c:401)
==26043==    by 0x4A613ED: _PyConfig_InitPathConfig (pathconfig.c:438)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 204 bytes in 1 blocks are still reachable in loss record 37 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A612DC: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A612DC: _PyConfig_InitPathConfig (pathconfig.c:458)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 204 bytes in 1 blocks are still reachable in loss record 38 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A605D1: copy_wstr (pathconfig.c:27)
==26043==    by 0x4A605D1: pathconfig_set_from_config (pathconfig.c:167)
==26043==    by 0x4A60C52: _PyConfig_WritePathConfig (pathconfig.c:267)
==26043==    by 0x4A659F0: interpreter_update_config (pylifecycle.c:457)
==26043==    by 0x4A659F0: init_interp_main (pylifecycle.c:1087)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 280 bytes in 1 blocks are still reachable in loss record 39 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A69ADA: new_threadstate (pystate.c:617)
==26043==    by 0x4A69ADA: PyThreadState_New (pystate.c:684)
==26043==    by 0x4A66FC8: pycore_create_interpreter (pylifecycle.c:640)
==26043==    by 0x4A66FC8: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66FC8: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 300 bytes in 1 blocks are still reachable in loss record 40 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A60769: _PyWideStringList_Join (pathconfig.c:123)
==26043==    by 0x4A60769: pathconfig_set_from_config (pathconfig.c:152)
==26043==    by 0x4A60C52: _PyConfig_WritePathConfig (pathconfig.c:267)
==26043==    by 0x4A659F0: interpreter_update_config (pylifecycle.c:457)
==26043==    by 0x4A659F0: init_interp_main (pylifecycle.c:1087)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 300 bytes in 3 blocks are still reachable in loss record 41 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x497ADE4: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x497ADE4: _PyMem_RawWcsdup (obmalloc.c:644)
==26043==    by 0x4A52006: PyWideStringList_Insert (initconfig.c:377)
==26043==    by 0x4A52006: PyWideStringList_Append (initconfig.c:405)
==26043==    by 0x4A611DF: config_init_module_search_paths (pathconfig.c:294)
==26043==    by 0x4A611DF: config_init_pathconfig (pathconfig.c:377)
==26043==    by 0x4A611DF: _PyConfig_InitPathConfig (pathconfig.c:438)
==26043==    by 0x4A65503: init_interp_main (pylifecycle.c:1082)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 518 bytes in 1 blocks are still reachable in loss record 42 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49DC9F9: unicode_decode_utf8 (unicodeobject.c:5203)
==26043==    by 0x4992B98: PyType_FromModuleAndSpec (typeobject.c:3569)
==26043==    by 0x4AD6899: thread_module_exec (_threadmodule.c:1594)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043== 
==26043== 535 bytes in 1 blocks are still reachable in loss record 43 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x491599F: _PyBytes_FromSize (bytesobject.c:126)
==26043==    by 0x491599F: PyBytes_FromStringAndSize (bytesobject.c:159)
==26043==    by 0x4A5C34C: r_object (marshal.c:1069)
==26043==    by 0x4A5B805: r_object (marshal.c:1347)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5CDE7: read_object (marshal.c:1445)
==26043==    by 0x4A5D023: marshal_loads_impl (marshal.c:1754)
==26043==    by 0x4A5D023: marshal_loads (marshal.c.h:148)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C77C1: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C77C1: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C77C1: call_function (ceval.c:5891)
==26043==    by 0x48C77C1: _PyEval_EvalFrameDefault (ceval.c:4181)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043== 
==26043== 540 bytes in 1 blocks are still reachable in loss record 44 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x491599F: _PyBytes_FromSize (bytesobject.c:126)
==26043==    by 0x491599F: PyBytes_FromStringAndSize (bytesobject.c:159)
==26043==    by 0x4A99C44: convertenviron (posixmodule.c:1640)
==26043==    by 0x4A99C44: posixmodule_exec (posixmodule.c:15706)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C77C1: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C77C1: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C77C1: call_function (ceval.c:5891)
==26043==    by 0x48C77C1: _PyEval_EvalFrameDefault (ceval.c:4181)
==26043== 
==26043== 567 bytes in 1 blocks are still reachable in loss record 45 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49DC9F9: unicode_decode_utf8 (unicodeobject.c:5203)
==26043==    by 0x498E5D8: type_dict_set_doc (typeobject.c:6074)
==26043==    by 0x498E5D8: type_ready_fill_dict (typeobject.c:6110)
==26043==    by 0x498E5D8: type_ready (typeobject.c:6339)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x4A1ED8F: _PyBuiltin_Init (bltinmodule.c:2983)
==26043==    by 0x4A63F7C: pycore_init_builtins (pylifecycle.c:745)
==26043==    by 0x4A63F7C: pycore_interp_init (pylifecycle.c:829)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043== 
==26043== 576 bytes in 1 blocks are still reachable in loss record 46 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x498E5F6: type_dict_set_doc (typeobject.c:6079)
==26043==    by 0x498E5F6: type_ready_fill_dict (typeobject.c:6110)
==26043==    by 0x498E5F6: type_ready (typeobject.c:6339)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x49848B9: _PyStructSequence_InitType (structseq.c:506)
==26043==    by 0x4AD383A: _PySignal_Init (signalmodule.c:1974)
==26043==    by 0x4A65B63: init_interp_main (pylifecycle.c:1110)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043== 
==26043== 586 bytes in 1 blocks are still reachable in loss record 47 of 94
==26043==    at 0x484582F: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x499DB16: resize_compact (unicodeobject.c:1079)
==26043==    by 0x49D604F: _PyUnicodeWriter_Finish (unicodeobject.c:14401)
==26043==    by 0x49DD8DF: unicode_decode_utf8 (unicodeobject.c:5317)
==26043==    by 0x4A5BD8B: r_object (marshal.c:1140)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5CDE7: read_object (marshal.c:1445)
==26043==    by 0x4A5E57F: PyMarshal_ReadObjectFromString (marshal.c:1562)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043== 
==26043== 720 bytes in 1 blocks are still reachable in loss record 48 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x4984826: _PyStructSequence_InitType (structseq.c:498)
==26043==    by 0x4A7C35C: _PySys_InitCore (sysmodule.c:2874)
==26043==    by 0x4A7C35C: _PySys_Create (sysmodule.c:3116)
==26043==    by 0x4A63F57: pycore_interp_init (pylifecycle.c:824)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 768 bytes in 1 blocks are still reachable in loss record 49 of 94
==26043==    at 0x48406C4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4979629: PyMem_RawRealloc (obmalloc.c:590)
==26043==    by 0x4979629: new_arena (obmalloc.c:1573)
==26043==    by 0x4979629: allocate_from_new_pool (obmalloc.c:1787)
==26043==    by 0x49797E4: pymalloc_alloc (obmalloc.c:1951)
==26043==    by 0x49797E4: _PyObject_Malloc (obmalloc.c:1961)
==26043==    by 0x495BE5E: _PyLong_New (longobject.c:138)
==26043==    by 0x495BE5E: _PyLong_Init (longobject.c:5771)
==26043==    by 0x4A63CF8: pycore_init_singletons (pylifecycle.c:661)
==26043==    by 0x4A63CF8: pycore_interp_init (pylifecycle.c:799)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 944 bytes in 1 blocks are still reachable in loss record 50 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x4A92724: _PyObject_GC_Alloc (gcmodule.c:2280)
==26043==    by 0x4A92724: _PyObject_GC_Malloc (gcmodule.c:2307)
==26043==    by 0x4989225: PyType_GenericAlloc (typeobject.c:1156)
==26043==    by 0x499B121: type_new_alloc (typeobject.c:2743)
==26043==    by 0x499B121: type_new_init (typeobject.c:3155)
==26043==    by 0x499B121: type_new_impl (typeobject.c:3178)
==26043==    by 0x499B121: type_new (typeobject.c:3327)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x4921A64: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x4921A64: PyObject_VectorcallDict (call.c:166)
==26043==    by 0x4A1D371: builtin___build_class__ (bltinmodule.c:224)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043== 
==26043== 1,024 bytes in 1 blocks are still reachable in loss record 51 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49799C9: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49799C9: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49799C9: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49799C9: pymalloc_realloc (obmalloc.c:2314)
==26043==    by 0x49799C9: _PyObject_Realloc (obmalloc.c:2333)
==26043==    by 0x49E33AC: _PyUnicode_FromId (unicodeobject.c:2379)
==26043==    by 0x4965000: _PyDict_ContainsId (dictobject.c:3427)
==26043==    by 0x4A4075F: PyErr_NewException (errors.c:1131)
==26043==    by 0x4AD19EF: signal_module_exec (signalmodule.c:1644)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043== 
==26043== 1,024 bytes in 1 blocks are still reachable in loss record 52 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x4AE0ACA: _buffered_init (bufferedio.c:732)
==26043==    by 0x4AE0C7E: _io_BufferedReader___init___impl (bufferedio.c:1447)
==26043==    by 0x4AE0C7E: _io_BufferedReader___init__ (bufferedio.c.h:435)
==26043==    by 0x498B116: type_call (typeobject.c:1135)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:112)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:99)
==26043==    by 0x49219B0: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x49227E3: _PyObject_CallFunction_SizeT (call.c:539)
==26043==    by 0x4ADAC48: _io_open_impl (_iomodule.c:465)
==26043==    by 0x4ADAC48: _io_open (_iomodule.c.h:269)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x492188A: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x492188A: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x4922B98: callmethod (call.c:557)
==26043==    by 0x4922B98: _PyObject_CallMethodId (call.c:627)
==26043== 
==26043== 1,056 bytes in 2 blocks are possibly lost in loss record 53 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49799C9: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49799C9: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49799C9: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49799C9: pymalloc_realloc (obmalloc.c:2314)
==26043==    by 0x49799C9: _PyObject_Realloc (obmalloc.c:2333)
==26043==    by 0x4A92DB4: _PyObject_GC_Resize (gcmodule.c:2356)
==26043==    by 0x48BE53C: frame_alloc (frameobject.c:812)
==26043==    by 0x48BE53C: _PyFrame_New_NoTrack (frameobject.c:840)
==26043==    by 0x4A225C5: _PyEval_MakeFrameVector (ceval.c:4790)
==26043==    by 0x4A232FE: _PyEval_Vector (ceval.c:5057)
==26043==    by 0x49216AE: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x49216AE: object_vacall (call.c:734)
==26043==    by 0x4923266: _PyObject_CallMethodIdObjArgs (call.c:825)
==26043==    by 0x4A4F8A4: PyImport_ImportModuleLevelObject (import.c:1694)
==26043==    by 0x48C76E7: import_name (ceval.c:6016)
==26043==    by 0x48C76E7: _PyEval_EvalFrameDefault (ceval.c:3695)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A1C378: builtin_exec_impl (bltinmodule.c:1056)
==26043==    by 0x4A1C378: builtin_exec (bltinmodule.c.h:371)
==26043== 
==26043== 1,236 bytes in 1 blocks are still reachable in loss record 54 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x499B345: type_new_set_doc (typeobject.c:2885)
==26043==    by 0x499B345: type_new_set_attrs (typeobject.c:3074)
==26043==    by 0x499B345: type_new_impl (typeobject.c:3183)
==26043==    by 0x499B345: type_new (typeobject.c:3327)
==26043==    by 0x498B30C: tp_new_wrapper (typeobject.c:7017)
==26043==    by 0x496F442: cfunction_call (methodobject.c:543)
==26043==    by 0x4921E8C: PyObject_Call (call.c:314)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x49224A4: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x49224A4: _PyObject_Call_Prepend (call.c:431)
==26043==    by 0x498701A: slot_tp_new (typeobject.c:7764)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043== 
==26043== 1,489 bytes in 1 blocks are still reachable in loss record 55 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x499B345: type_new_set_doc (typeobject.c:2885)
==26043==    by 0x499B345: type_new_set_attrs (typeobject.c:3074)
==26043==    by 0x499B345: type_new_impl (typeobject.c:3183)
==26043==    by 0x499B345: type_new (typeobject.c:3327)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x4921A64: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x4921A64: PyObject_VectorcallDict (call.c:166)
==26043==    by 0x4A1D371: builtin___build_class__ (bltinmodule.c:224)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A4F319: exec_code_in_module (import.c:793)
==26043==    by 0x4A4F319: PyImport_ImportFrozenModuleObject (import.c:1195)
==26043==    by 0x4A4F5E9: PyImport_ImportFrozenModule (import.c:1217)
==26043== 
==26043== 1,522 bytes in 1 blocks are still reachable in loss record 56 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49DC9F9: unicode_decode_utf8 (unicodeobject.c:5203)
==26043==    by 0x4971977: PyModule_SetDocString (moduleobject.c:455)
==26043==    by 0x4971977: _PyModule_CreateInitialized (moduleobject.c:238)
==26043==    by 0x4ADB048: PyInit__io (_iomodule.c:693)
==26043==    by 0x4A4E907: create_builtin.part.0.isra.0 (import.c:1013)
==26043==    by 0x4A4EA1F: create_builtin (import.c:1000)
==26043==    by 0x4A4EA1F: _imp_create_builtin (import.c:1064)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043== 
==26043== 1,688 bytes in 2 blocks are still reachable in loss record 57 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x496520D: PyDict_SetItem (dictobject.c:1623)
==26043==    by 0x496520D: PyDict_SetItemString (dictobject.c:3614)
==26043==    by 0x498391C: initialize_structseq_dict (structseq.c:402)
==26043==    by 0x49848D7: _PyStructSequence_InitType (structseq.c:512)
==26043==    by 0x4A7C35C: _PySys_InitCore (sysmodule.c:2874)
==26043==    by 0x4A7C35C: _PySys_Create (sysmodule.c:3116)
==26043==    by 0x4A63F57: pycore_interp_init (pylifecycle.c:824)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043== 
==26043== 1,829 bytes in 2 blocks are still reachable in loss record 58 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49DC9F9: unicode_decode_utf8 (unicodeobject.c:5203)
==26043==    by 0x49926F3: type_getattro (typeobject.c:3956)
==26043==    by 0x4973C17: PyObject_GetAttr (object.c:932)
==26043==    by 0x48C328B: _PyEval_EvalFrameDefault (ceval.c:3592)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A1D30B: builtin___build_class__ (bltinmodule.c:216)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x48C4C78: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C4C78: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C4C78: call_function (ceval.c:5891)
==26043==    by 0x48C4C78: _PyEval_EvalFrameDefault (ceval.c:4231)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043== 
==26043== 2,048 bytes in 1 blocks are still reachable in loss record 59 of 94
==26043==    at 0x48455EF: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4978EB2: PyMem_RawCalloc (obmalloc.c:581)
==26043==    by 0x4978EB2: arena_map_get (obmalloc.c:1435)
==26043==    by 0x4978EB2: arena_map_mark_used (obmalloc.c:1478)
==26043==    by 0x4979473: new_arena (obmalloc.c:1607)
==26043==    by 0x4979473: allocate_from_new_pool (obmalloc.c:1787)
==26043==    by 0x49797E4: pymalloc_alloc (obmalloc.c:1951)
==26043==    by 0x49797E4: _PyObject_Malloc (obmalloc.c:1961)
==26043==    by 0x495BE5E: _PyLong_New (longobject.c:138)
==26043==    by 0x495BE5E: _PyLong_Init (longobject.c:5771)
==26043==    by 0x4A63CF8: pycore_init_singletons (pylifecycle.c:661)
==26043==    by 0x4A63CF8: pycore_interp_init (pylifecycle.c:799)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 2,048 bytes in 2 blocks are still reachable in loss record 60 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x4AE0ACA: _buffered_init (bufferedio.c:732)
==26043==    by 0x4AE12DE: _io_BufferedWriter___init___impl (bufferedio.c:1801)
==26043==    by 0x4AE12DE: _io_BufferedWriter___init__ (bufferedio.c.h:489)
==26043==    by 0x498B116: type_call (typeobject.c:1135)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:112)
==26043==    by 0x49219B0: _PyObject_VectorcallTstate (abstract.h:99)
==26043==    by 0x49219B0: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x49227E3: _PyObject_CallFunction_SizeT (call.c:539)
==26043==    by 0x4ADAC48: _io_open_impl (_iomodule.c:465)
==26043==    by 0x4ADAC48: _io_open (_iomodule.c.h:269)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x492188A: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x492188A: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x4922B98: callmethod (call.c:557)
==26043==    by 0x4922B98: _PyObject_CallMethodId (call.c:627)
==26043== 
==26043== 2,057 bytes in 2 blocks are still reachable in loss record 61 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49A98DC: _PyUnicode_FromUCS1 (unicodeobject.c:2463)
==26043==    by 0x4A5B6B6: r_object (marshal.c:1112)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5CDE7: read_object (marshal.c:1445)
==26043==    by 0x4A5E57F: PyMarshal_ReadObjectFromString (marshal.c:1562)
==26043==    by 0x4A4F2CE: PyImport_ImportFrozenModuleObject (import.c:1163)
==26043== 
==26043== 2,208 bytes in 1 blocks are still reachable in loss record 62 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x48C5CA6: _PyEval_EvalFrameDefault (ceval.c:2770)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A4F319: exec_code_in_module (import.c:793)
==26043==    by 0x4A4F319: PyImport_ImportFrozenModuleObject (import.c:1195)
==26043==    by 0x4A4F5E9: PyImport_ImportFrozenModule (import.c:1217)
==26043==    by 0x4A642F7: init_importlib (pylifecycle.c:167)
==26043==    by 0x4A642F7: pycore_interp_init (pylifecycle.c:837)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043== 
==26043== 2,208 bytes in 1 blocks are still reachable in loss record 63 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x496520D: PyDict_SetItem (dictobject.c:1623)
==26043==    by 0x496520D: PyDict_SetItemString (dictobject.c:3614)
==26043==    by 0x4A5FDED: PyModule_AddObjectRef (modsupport.c:662)
==26043==    by 0x4A5FDED: PyModule_AddIntConstant (modsupport.c:686)
==26043==    by 0x4AD1C06: signal_add_constants (signalmodule.c:1501)
==26043==    by 0x4AD1C06: signal_module_exec (signalmodule.c:1651)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043== 
==26043== 2,304 bytes in 4 blocks are still reachable in loss record 64 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x496450A: insertion_resize (dictobject.c:1060)
==26043==    by 0x496450A: PyDict_SetDefault (dictobject.c:3067)
==26043==    by 0x498E575: type_add_getset (typeobject.c:5672)
==26043==    by 0x498E575: type_ready_fill_dict (typeobject.c:6107)
==26043==    by 0x498E575: type_ready (typeobject.c:6339)
==26043==    by 0x499B5CB: PyType_Ready (typeobject.c:6372)
==26043==    by 0x499B5CB: type_new_impl (typeobject.c:3188)
==26043==    by 0x499B5CB: type_new (typeobject.c:3327)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x4921A64: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x4921A64: PyObject_VectorcallDict (call.c:166)
==26043==    by 0x4A1D371: builtin___build_class__ (bltinmodule.c:224)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043== 
==26043== 2,318 bytes in 3 blocks are still reachable in loss record 65 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x499B345: type_new_set_doc (typeobject.c:2885)
==26043==    by 0x499B345: type_new_set_attrs (typeobject.c:3074)
==26043==    by 0x499B345: type_new_impl (typeobject.c:3183)
==26043==    by 0x499B345: type_new (typeobject.c:3327)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x4921A64: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x4921A64: PyObject_VectorcallDict (call.c:166)
==26043==    by 0x4A1D371: builtin___build_class__ (bltinmodule.c:224)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A1C378: builtin_exec_impl (bltinmodule.c:1056)
==26043==    by 0x4A1C378: builtin_exec (bltinmodule.c.h:371)
==26043==    by 0x496FBEC: cfunction_vectorcall_FASTCALL (methodobject.c:430)
==26043== 
==26043== 2,449 bytes in 3 blocks are still reachable in loss record 66 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x491599F: _PyBytes_FromSize (bytesobject.c:126)
==26043==    by 0x491599F: PyBytes_FromStringAndSize (bytesobject.c:159)
==26043==    by 0x4A5C34C: r_object (marshal.c:1069)
==26043==    by 0x4A5B805: r_object (marshal.c:1347)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5CDE7: read_object (marshal.c:1445)
==26043==    by 0x4A5E57F: PyMarshal_ReadObjectFromString (marshal.c:1562)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043== 
==26043== 3,040 bytes in 1 blocks are still reachable in loss record 67 of 94
==26043==    at 0x484582F: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x494BDB2: list_resize (listobject.c:82)
==26043==    by 0x494BDB2: list_extend (listobject.c:907)
==26043==    by 0x492C2D8: method_vectorcall_O (descrobject.c:460)
==26043==    by 0x48C4E5F: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C4E5F: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C4E5F: call_function (ceval.c:5891)
==26043==    by 0x48C4E5F: _PyEval_EvalFrameDefault (ceval.c:4198)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A1C378: builtin_exec_impl (bltinmodule.c:1056)
==26043==    by 0x4A1C378: builtin_exec (bltinmodule.c.h:371)
==26043==    by 0x496FBEC: cfunction_vectorcall_FASTCALL (methodobject.c:430)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C77C1: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C77C1: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C77C1: call_function (ceval.c:5891)
==26043==    by 0x48C77C1: _PyEval_EvalFrameDefault (ceval.c:4181)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C4E5F: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C4E5F: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C4E5F: call_function (ceval.c:5891)
==26043==    by 0x48C4E5F: _PyEval_EvalFrameDefault (ceval.c:4198)
==26043== 
==26043== 3,136 bytes in 5 blocks are still reachable in loss record 68 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49A98DC: _PyUnicode_FromUCS1 (unicodeobject.c:2463)
==26043==    by 0x4A5B6B6: r_object (marshal.c:1112)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5CDE7: read_object (marshal.c:1445)
==26043==    by 0x4A5E57F: PyMarshal_ReadObjectFromString (marshal.c:1562)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043== 
==26043== 3,304 bytes in 6 blocks are possibly lost in loss record 69 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x4A92BDE: _PyObject_GC_Alloc (gcmodule.c:2280)
==26043==    by 0x4A92BDE: _PyObject_GC_Malloc (gcmodule.c:2307)
==26043==    by 0x4A92BDE: _PyObject_GC_NewVar (gcmodule.c:2338)
==26043==    by 0x48BE560: frame_alloc (frameobject.c:797)
==26043==    by 0x48BE560: _PyFrame_New_NoTrack (frameobject.c:840)
==26043==    by 0x4A225C5: _PyEval_MakeFrameVector (ceval.c:4790)
==26043==    by 0x4A232FE: _PyEval_Vector (ceval.c:5057)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x49216AE: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x49216AE: object_vacall (call.c:734)
==26043==    by 0x4923266: _PyObject_CallMethodIdObjArgs (call.c:825)
==26043== 
==26043== 3,456 bytes in 6 blocks are still reachable in loss record 70 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495CB0B: clone_combined_dict_keys (dictobject.c:709)
==26043==    by 0x49636BC: PyDict_Copy (dictobject.c:2811)
==26043==    by 0x499ABEE: type_new_init (typeobject.c:3141)
==26043==    by 0x499ABEE: type_new_impl (typeobject.c:3178)
==26043==    by 0x499ABEE: type_new (typeobject.c:3327)
==26043==    by 0x498B30C: tp_new_wrapper (typeobject.c:7017)
==26043==    by 0x496F442: cfunction_call (methodobject.c:543)
==26043==    by 0x4921E8C: PyObject_Call (call.c:314)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x49224A4: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x49224A4: _PyObject_Call_Prepend (call.c:431)
==26043==    by 0x498701A: slot_tp_new (typeobject.c:7764)
==26043== 
==26043== 4,632 bytes in 1 blocks are still reachable in loss record 71 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C4EE: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x496520D: PyDict_SetItem (dictobject.c:1623)
==26043==    by 0x496520D: PyDict_SetItemString (dictobject.c:3614)
==26043==    by 0x4A7AE6B: _PySys_UpdateConfig (sysmodule.c:3020)
==26043==    by 0x4A65544: interpreter_update_config (pylifecycle.c:465)
==26043==    by 0x4A65544: init_interp_main (pylifecycle.c:1087)
==26043==    by 0x4A663F4: pyinit_main (pylifecycle.c:1195)
==26043==    by 0x4A6783A: Py_InitializeFromConfig (pylifecycle.c:1226)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043== 
==26043== 4,632 bytes in 1 blocks are still reachable in loss record 72 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C4EE: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x496520D: PyDict_SetItem (dictobject.c:1623)
==26043==    by 0x496520D: PyDict_SetItemString (dictobject.c:3614)
==26043==    by 0x4A9AD4B: setup_confname_table (posixmodule.c:12442)
==26043==    by 0x4A9AD4B: setup_confname_tables (posixmodule.c:12471)
==26043==    by 0x4A9AD4B: posixmodule_exec (posixmodule.c:15715)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043== 
==26043== 4,632 bytes in 1 blocks are still reachable in loss record 73 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C4EE: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x48C5CA6: _PyEval_EvalFrameDefault (ceval.c:2770)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A1C378: builtin_exec_impl (bltinmodule.c:1056)
==26043==    by 0x4A1C378: builtin_exec (bltinmodule.c.h:371)
==26043==    by 0x496FBEC: cfunction_vectorcall_FASTCALL (methodobject.c:430)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C77C1: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C77C1: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C77C1: call_function (ceval.c:5891)
==26043==    by 0x48C77C1: _PyEval_EvalFrameDefault (ceval.c:4181)
==26043== 
==26043== 5,568 bytes in 4 blocks are still reachable in loss record 74 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x496450A: insertion_resize (dictobject.c:1060)
==26043==    by 0x496450A: PyDict_SetDefault (dictobject.c:3067)
==26043==    by 0x498E505: type_add_members (typeobject.c:5647)
==26043==    by 0x498E505: type_ready_fill_dict (typeobject.c:6104)
==26043==    by 0x498E505: type_ready (typeobject.c:6339)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x49848B9: _PyStructSequence_InitType (structseq.c:506)
==26043==    by 0x4AD4AB2: time_exec (timemodule.c:1999)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043== 
==26043== 5,624 bytes in 6 blocks are still reachable in loss record 75 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x496520D: PyDict_SetItem (dictobject.c:1623)
==26043==    by 0x496520D: PyDict_SetItemString (dictobject.c:3614)
==26043==    by 0x4A5FDED: PyModule_AddObjectRef (modsupport.c:662)
==26043==    by 0x4A5FDED: PyModule_AddIntConstant (modsupport.c:686)
==26043==    by 0x4AD3C42: stat_exec (_stat.c:537)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043== 
==26043== 6,200 bytes in 7 blocks are still reachable in loss record 76 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x496450A: insertion_resize (dictobject.c:1060)
==26043==    by 0x496450A: PyDict_SetDefault (dictobject.c:3067)
==26043==    by 0x498E505: type_add_members (typeobject.c:5647)
==26043==    by 0x498E505: type_ready_fill_dict (typeobject.c:6104)
==26043==    by 0x498E505: type_ready (typeobject.c:6339)
==26043==    by 0x4992B51: PyType_Ready (typeobject.c:6372)
==26043==    by 0x4992B51: PyType_FromModuleAndSpec (typeobject.c:3561)
==26043==    by 0x4AD68CC: thread_module_exec (_threadmodule.c:1603)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043== 
==26043== 6,336 bytes in 11 blocks are still reachable in loss record 77 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495CB0B: clone_combined_dict_keys (dictobject.c:709)
==26043==    by 0x49636BC: PyDict_Copy (dictobject.c:2811)
==26043==    by 0x499ABEE: type_new_init (typeobject.c:3141)
==26043==    by 0x499ABEE: type_new_impl (typeobject.c:3178)
==26043==    by 0x499ABEE: type_new (typeobject.c:3327)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x4921A64: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x4921A64: PyObject_VectorcallDict (call.c:166)
==26043==    by 0x4A1D371: builtin___build_class__ (bltinmodule.c:224)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043== 
==26043== 6,556 bytes in 6 blocks are still reachable in loss record 78 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49DC9F9: unicode_decode_utf8 (unicodeobject.c:5203)
==26043==    by 0x498E5D8: type_dict_set_doc (typeobject.c:6074)
==26043==    by 0x498E5D8: type_ready_fill_dict (typeobject.c:6110)
==26043==    by 0x498E5D8: type_ready (typeobject.c:6339)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x49904AA: type_ready_set_bases (typeobject.c:6007)
==26043==    by 0x49904AA: type_ready (typeobject.c:6330)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x4975BA6: _PyTypes_Init (object.c:1811)
==26043==    by 0x4A64094: pycore_init_types (pylifecycle.c:699)
==26043==    by 0x4A64094: pycore_interp_init (pylifecycle.c:810)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043== 
==26043== 6,832 bytes in 10 blocks are still reachable in loss record 79 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x496520D: PyDict_SetItem (dictobject.c:1623)
==26043==    by 0x496520D: PyDict_SetItemString (dictobject.c:3614)
==26043==    by 0x4A9AC0B: setup_confname_table (posixmodule.c:12442)
==26043==    by 0x4A9AC0B: setup_confname_tables (posixmodule.c:12457)
==26043==    by 0x4A9AC0B: posixmodule_exec (posixmodule.c:15715)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043== 
==26043== 8,192 bytes in 1 blocks are still reachable in loss record 80 of 94
==26043==    at 0x48455EF: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4978EEA: PyMem_RawCalloc (obmalloc.c:581)
==26043==    by 0x4978EEA: arena_map_get (obmalloc.c:1423)
==26043==    by 0x4978EEA: arena_map_mark_used (obmalloc.c:1478)
==26043==    by 0x4979473: new_arena (obmalloc.c:1607)
==26043==    by 0x4979473: allocate_from_new_pool (obmalloc.c:1787)
==26043==    by 0x49797E4: pymalloc_alloc (obmalloc.c:1951)
==26043==    by 0x49797E4: _PyObject_Malloc (obmalloc.c:1961)
==26043==    by 0x495BE5E: _PyLong_New (longobject.c:138)
==26043==    by 0x495BE5E: _PyLong_Init (longobject.c:5771)
==26043==    by 0x4A63CF8: pycore_init_singletons (pylifecycle.c:661)
==26043==    by 0x4A63CF8: pycore_interp_init (pylifecycle.c:799)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 8,192 bytes in 1 blocks are still reachable in loss record 81 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x497DF68: set_table_resize (setobject.c:274)
==26043==    by 0x497E7B8: set_add_key (setobject.c:354)
==26043==    by 0x497E7B8: set_update_internal (setobject.c:917)
==26043==    by 0x497E7B8: set_update_internal (setobject.c:882)
==26043==    by 0x49806FA: make_new_set (setobject.c:971)
==26043==    by 0x49806FA: make_new_frozenset (setobject.c:1004)
==26043==    by 0x49806FA: make_new_frozenset (setobject.c:993)
==26043==    by 0x49806FA: frozenset_vectorcall (setobject.c:1037)
==26043==    by 0x492188A: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x492188A: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x4922680: PyObject_CallFunction (call.c:507)
==26043==    by 0x4A7BD20: list_stdlib_module_names (sysmodule.c:2127)
==26043==    by 0x4A7BD20: _PySys_InitCore (sysmodule.c:2843)
==26043==    by 0x4A7BD20: _PySys_Create (sysmodule.c:3116)
==26043==    by 0x4A63F57: pycore_interp_init (pylifecycle.c:824)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043== 
==26043== 9,248 bytes in 1 blocks are still reachable in loss record 82 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C4EE: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x496520D: PyDict_SetItem (dictobject.c:1623)
==26043==    by 0x496520D: PyDict_SetItemString (dictobject.c:3614)
==26043==    by 0x4A5FDED: PyModule_AddObjectRef (modsupport.c:662)
==26043==    by 0x4A5FDED: PyModule_AddIntConstant (modsupport.c:686)
==26043==    by 0x4A99D12: all_ins (posixmodule.c:14926)
==26043==    by 0x4A99D12: posixmodule_exec (posixmodule.c:15712)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043==    by 0x4A4D79A: _imp_exec_builtin (import.c.h:383)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043== 
==26043== 9,264 bytes in 2 blocks are still reachable in loss record 83 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C4EE: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x498747B: add_subclass (typeobject.c:6411)
==26043==    by 0x498ECA2: type_ready_add_subclasses (typeobject.c:6258)
==26043==    by 0x498ECA2: type_ready (typeobject.c:6348)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x49333DB: _PyExc_Init (exceptions.c:2686)
==26043==    by 0x4A63E32: pycore_init_types (pylifecycle.c:720)
==26043==    by 0x4A63E32: pycore_interp_init (pylifecycle.c:810)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043== 
==26043== 9,274 bytes in 8 blocks are still reachable in loss record 84 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49DC9F9: unicode_decode_utf8 (unicodeobject.c:5203)
==26043==    by 0x498E5D8: type_dict_set_doc (typeobject.c:6074)
==26043==    by 0x498E5D8: type_ready_fill_dict (typeobject.c:6110)
==26043==    by 0x498E5D8: type_ready (typeobject.c:6339)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x4A5FF31: PyModule_AddType (modsupport.c:706)
==26043==    by 0x4ADB10B: PyInit__io (_iomodule.c:729)
==26043==    by 0x4A4E907: create_builtin.part.0.isra.0 (import.c:1013)
==26043==    by 0x4A4EA1F: create_builtin (import.c:1000)
==26043==    by 0x4A4EA1F: _imp_create_builtin (import.c:1064)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043== 
==26043== 10,200 bytes in 5 blocks are still reachable in loss record 85 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495CB0B: clone_combined_dict_keys (dictobject.c:709)
==26043==    by 0x49636BC: PyDict_Copy (dictobject.c:2811)
==26043==    by 0x4A4E69F: _PyImport_FixupExtensionObject (import.c:458)
==26043==    by 0x4A4E74E: _PyImport_FixupBuiltin (import.c:493)
==26043==    by 0x4A7C310: _PySys_Create (sysmodule.c:3121)
==26043==    by 0x4A63F57: pycore_interp_init (pylifecycle.c:824)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043== 
==26043== 11,168 bytes in 10 blocks are still reachable in loss record 86 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x48C5CA6: _PyEval_EvalFrameDefault (ceval.c:2770)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A1C378: builtin_exec_impl (bltinmodule.c:1056)
==26043==    by 0x4A1C378: builtin_exec (bltinmodule.c.h:371)
==26043==    by 0x496FBEC: cfunction_vectorcall_FASTCALL (methodobject.c:430)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C77C1: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C77C1: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C77C1: call_function (ceval.c:5891)
==26043==    by 0x48C77C1: _PyEval_EvalFrameDefault (ceval.c:4181)
==26043== 
==26043== 15,040 bytes in 13 blocks are still reachable in loss record 87 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x496450A: insertion_resize (dictobject.c:1060)
==26043==    by 0x496450A: PyDict_SetDefault (dictobject.c:3067)
==26043==    by 0x498E392: type_add_method (typeobject.c:5599)
==26043==    by 0x498E392: type_add_methods (typeobject.c:5625)
==26043==    by 0x498E392: type_ready_fill_dict (typeobject.c:6101)
==26043==    by 0x498E392: type_ready (typeobject.c:6339)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x4A5FF31: PyModule_AddType (modsupport.c:706)
==26043==    by 0x4ADB10B: PyInit__io (_iomodule.c:729)
==26043==    by 0x4A4E907: create_builtin.part.0.isra.0 (import.c:1013)
==26043==    by 0x4A4EA1F: create_builtin (import.c:1000)
==26043==    by 0x4A4EA1F: _imp_create_builtin (import.c:1064)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043== 
==26043== 16,384 bytes in 2 blocks are still reachable in loss record 88 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x497DF68: set_table_resize (setobject.c:274)
==26043==    by 0x497E7B8: set_add_key (setobject.c:354)
==26043==    by 0x497E7B8: set_update_internal (setobject.c:917)
==26043==    by 0x497E7B8: set_update_internal (setobject.c:882)
==26043==    by 0x4980465: make_new_set (setobject.c:971)
==26043==    by 0x4980465: set_vectorcall (setobject.c:2006)
==26043==    by 0x4980465: set_vectorcall (setobject.c:1991)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C4E5F: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C4E5F: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C4E5F: call_function (ceval.c:5891)
==26043==    by 0x48C4E5F: _PyEval_EvalFrameDefault (ceval.c:4198)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x48C4E5F: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C4E5F: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C4E5F: call_function (ceval.c:5891)
==26043==    by 0x48C4E5F: _PyEval_EvalFrameDefault (ceval.c:4198)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4924817: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x4924817: method_vectorcall (classobject.c:53)
==26043== 
==26043== 26,472 bytes in 26 blocks are still reachable in loss record 89 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x49A9377: PyUnicode_New (unicodeobject.c:1463)
==26043==    by 0x49A98DC: _PyUnicode_FromUCS1 (unicodeobject.c:2463)
==26043==    by 0x4A5B6B6: r_object (marshal.c:1112)
==26043==    by 0x4A5BEE1: r_object (marshal.c:1174)
==26043==    by 0x4A5B81B: r_object (marshal.c:1350)
==26043==    by 0x4A5CDE7: read_object (marshal.c:1445)
==26043==    by 0x4A5E57F: PyMarshal_ReadObjectFromString (marshal.c:1562)
==26043==    by 0x496F809: cfunction_vectorcall_O (methodobject.c:516)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043== 
==26043== 32,136 bytes in 34 blocks are still reachable in loss record 90 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x4A92724: _PyObject_GC_Alloc (gcmodule.c:2280)
==26043==    by 0x4A92724: _PyObject_GC_Malloc (gcmodule.c:2307)
==26043==    by 0x4989225: PyType_GenericAlloc (typeobject.c:1156)
==26043==    by 0x499AFF9: type_new_alloc (typeobject.c:2743)
==26043==    by 0x499AFF9: type_new_init (typeobject.c:3155)
==26043==    by 0x499AFF9: type_new_impl (typeobject.c:3178)
==26043==    by 0x499AFF9: type_new (typeobject.c:3327)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x492188A: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x492188A: _PyObject_CallFunctionVa (call.c:485)
==26043==    by 0x4922680: PyObject_CallFunction (call.c:507)
==26043==    by 0x4A406AA: PyErr_NewException (errors.c:1153)
==26043==    by 0x4AD19EF: signal_module_exec (signalmodule.c:1644)
==26043==    by 0x4971733: PyModule_ExecDef (moduleobject.c:407)
==26043== 
==26043== 52,200 bytes in 54 blocks are still reachable in loss record 91 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C606: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x496450A: insertion_resize (dictobject.c:1060)
==26043==    by 0x496450A: PyDict_SetDefault (dictobject.c:3067)
==26043==    by 0x498E575: type_add_getset (typeobject.c:5672)
==26043==    by 0x498E575: type_ready_fill_dict (typeobject.c:6107)
==26043==    by 0x498E575: type_ready (typeobject.c:6339)
==26043==    by 0x498D1A1: PyType_Ready (typeobject.c:6372)
==26043==    by 0x4975B6A: _PyTypes_Init (object.c:1804)
==26043==    by 0x4A64094: pycore_init_types (pylifecycle.c:699)
==26043==    by 0x4A64094: pycore_interp_init (pylifecycle.c:810)
==26043==    by 0x4A67182: pyinit_config (pylifecycle.c:866)
==26043==    by 0x4A67182: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043== 
==26043== 56,792 bytes in 58 blocks are still reachable in loss record 92 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x4A92724: _PyObject_GC_Alloc (gcmodule.c:2280)
==26043==    by 0x4A92724: _PyObject_GC_Malloc (gcmodule.c:2307)
==26043==    by 0x4989225: PyType_GenericAlloc (typeobject.c:1156)
==26043==    by 0x499AFF9: type_new_alloc (typeobject.c:2743)
==26043==    by 0x499AFF9: type_new_init (typeobject.c:3155)
==26043==    by 0x499AFF9: type_new_impl (typeobject.c:3178)
==26043==    by 0x499AFF9: type_new (typeobject.c:3327)
==26043==    by 0x498B0A8: type_call (typeobject.c:1123)
==26043==    by 0x492116C: _PyObject_MakeTpCall (call.c:215)
==26043==    by 0x4921A64: _PyObject_FastCallDictTstate (call.c:142)
==26043==    by 0x4921A64: PyObject_VectorcallDict (call.c:166)
==26043==    by 0x4A1D371: builtin___build_class__ (bltinmodule.c:224)
==26043==    by 0x496FA84: cfunction_vectorcall_FASTCALL_KEYWORDS (methodobject.c:446)
==26043==    by 0x48C5F6B: _PyObject_VectorcallTstate (abstract.h:114)
==26043==    by 0x48C5F6B: PyObject_Vectorcall (abstract.h:123)
==26043==    by 0x48C5F6B: call_function (ceval.c:5891)
==26043==    by 0x48C5F6B: _PyEval_EvalFrameDefault (ceval.c:4213)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043== 
==26043== 113,528 bytes in 1 blocks are still reachable in loss record 93 of 94
==26043==    at 0x48455EF: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x4A694BB: PyInterpreterState_New (pystate.c:216)
==26043==    by 0x4A66F84: pycore_create_interpreter (pylifecycle.c:629)
==26043==    by 0x4A66F84: pyinit_config (pylifecycle.c:860)
==26043==    by 0x4A66F84: pyinit_core.constprop.0 (pylifecycle.c:1029)
==26043==    by 0x4A677AE: Py_InitializeFromConfig (pylifecycle.c:1219)
==26043==    by 0x4A8E8CA: pymain_init (main.c:66)
==26043==    by 0x4A8FBAE: pymain_main (main.c:687)
==26043==    by 0x4A8FBAE: Py_BytesMain (main.c:720)
==26043==    by 0x4C4E189: (below main) (libc_start_call_main.h:58)
==26043== 
==26043== 179,824 bytes in 4 blocks are still reachable in loss record 94 of 94
==26043==    at 0x48407B4: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==26043==    by 0x49797FF: PyMem_RawMalloc (obmalloc.c:572)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1966)
==26043==    by 0x49797FF: _PyObject_Malloc (obmalloc.c:1959)
==26043==    by 0x495C4EE: new_keys_object (dictobject.c:600)
==26043==    by 0x495C780: dictresize (dictobject.c:1242)
==26043==    by 0x495FC6A: insertion_resize (dictobject.c:1060)
==26043==    by 0x495FC6A: insertdict (dictobject.c:1103)
==26043==    by 0x4960562: dict_merge (dictobject.c:2639)
==26043==    by 0x48C0826: _PyEval_EvalFrameDefault (ceval.c:3362)
==26043==    by 0x4A2315D: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2315D: _PyEval_Vector (ceval.c:5065)
==26043==    by 0x4A2315D: PyEval_EvalCode (ceval.c:1134)
==26043==    by 0x4A1C378: builtin_exec_impl (bltinmodule.c:1056)
==26043==    by 0x4A1C378: builtin_exec (bltinmodule.c.h:371)
==26043==    by 0x496FBEC: cfunction_vectorcall_FASTCALL (methodobject.c:430)
==26043==    by 0x48C36CE: do_call_core (ceval.c:5943)
==26043==    by 0x48C36CE: _PyEval_EvalFrameDefault (ceval.c:4277)
==26043==    by 0x4A2332F: _PyEval_EvalFrame (pycore_ceval.h:46)
==26043==    by 0x4A2332F: _PyEval_Vector (ceval.c:5065)
==26043== 
==26043== LEAK SUMMARY:
==26043==    definitely lost: 0 bytes in 0 blocks
==26043==    indirectly lost: 0 bytes in 0 blocks
==26043==      possibly lost: 4,360 bytes in 8 blocks
==26043==    still reachable: 654,399 bytes in 365 blocks
==26043==         suppressed: 0 bytes in 0 blocks
==26043== 
==26043== For lists of detected and suppressed errors, rerun with: -s
==26043== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
